# Generated by Django 6.0.1 on 2026-01-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('client_type', models.CharField(choices=[('household', 'Ménage'), ('business', 'Commerce'), ('restaurant', 'Restaurant')], default='household', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية')], default='fr', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('late', 'En retard de paiement')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GasBottleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_mru', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_mru', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='core.bus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_mru', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.bus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='core.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'À visiter'), ('completed', 'Visité'), ('skipped', 'Non visité')], default='pending', max_length=20)),
                ('delivered_bottles', models.IntegerField(default=0)),
                ('returned_bottles', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_stops', to='core.client')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.tour')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_mru', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientBottleBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_balances', to='core.client')),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gasbottletype')),
            ],
            options={
                'unique_together': {('client', 'bottle_type')},
            },
        ),
        migrations.CreateModel(
            name='BusPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('on_tour', 'En tournée'), ('paused', 'En pause'), ('returning', 'Retour dépôt'), ('offline', 'Hors ligne')], default='on_tour', max_length=20)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.bus')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.tour')),
            ],
            options={
                'indexes': [models.Index(fields=['bus', 'created_at'], name='core_buspos_bus_id_a7a84a_idx')],
            },
        ),
    ]
