# Generated by Django 6.0.1 on 2026-01-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_warehouse_busbottlestock_warehousebottlestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(default='household', max_length=50),
        ),
    ]
