# Generated by Django 6.0.1 on 2026-01-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_geofencezone_bus_max_speed_kmh_busalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofencezone',
            name='polygon',
            field=models.JSONField(blank=True, help_text='Liste de points [lat, lon] décrivant un polygone', null=True),
        ),
        migrations.AlterField(
            model_name='geofencezone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='geofencezone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='geofencezone',
            name='radius_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Rayon du périmètre en mètres', null=True),
        ),
    ]
