# Generated by Django 6.0.1 on 2026-01-17 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_user_driver_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_mru', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price_mru', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.gasbottletype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
