# Generated by Django 6.0.1 on 2026-01-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('pending_admin', 'En attente administration'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('pending_admin', 'En attente administration'), ('validated', 'Validé'), ('rejected', 'Rejeté')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('pending_admin', 'En attente administration'), ('validated', 'Validé'), ('rejected', 'Rejeté')], max_length=20, null=True),
        ),
    ]
