# Generated by Django 6.0.1 on 2026-01-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('bankily', 'Bankily'), ('masrvi', 'Masrvi'), ('sedad', 'Sedad'), ('click', 'Click'), ('autre', 'Autre')], max_length=50),
        ),
    ]
