# Generated by Django 6.0.1 on 2026-01-18 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='core.driver'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
